env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "CirrusCI"
    CIRRUS_WORKING_DIR: "/tmp/ci"
    TOKEN: "ENCRYPTED[df92376488018baa89ee8f2b0d43eaae16224de669d67bce5261d4bd3031c7c9203742a610c5410ffe9eb89a5a9ca275]"
    VERSIONS: "0.3.4.4-AikoCute"
    INFORELEASE: "X-UI Vietnamese Language\n\nNgưng support 32Bit\nThêm Bot Telegram và CloudFlare\nChấp nhận clear dung lượng đã dùng\nThông báo dung lượng qua Telegram\n\nSupport: amd64, arm64v8a, s390x.\n\n*** Vui lòng tạo Issues nếu có bất kỳ lỗi nào"
    DEBIAN_FRONTEND: "noninteractive"
    SSHKEY1: "ENCRYPTED[293cefeab7ac826d4338d7754ffdf9c6601927edf806809e067e7f939210dcbe642f6d9791edf819e4a27842bcfc1f21]"
    SSHKEY2: "ENCRYPTED[5d133af9570c87e3668778d042e901f56033f7494b0b4f33e80319bd01bc58261c3c81516306af985183cd35ff16f7ac]"
    USERNAME: "ENCRYPTED[83bbe1770c3805ba3c246dbce1b3fd4741041b2e79d9ce7b497205bc0dccd3a202aef0e3110bc3cdc83b7b58073baf76]"
    EMAIL: "ENCRYPTED[0d359a6ad7f05df414539e7cc0af7d12393669897e6ad7b66b396ed403227cda156ce559593eead6657bd299bd068912]"

task:
  name: Compile X-UI
  only_if: $CIRRUS_REPO_OWNER == 'AikoCute-Offical' && $CIRRUS_BRANCH == 'main'
  skip: $CIRRUS_BRANCH != 'main'
  container:
    image: dopaemon/bionic:latest
    cpu: 4
    memory: 8G
  install_packages_script:
    - sudo rm -rf /tmp/ci/*
    - sudo apt update
    - sudo apt install software-properties-common jq wget unzip rclone aria2 git gcc-riscv64-linux-gnu gcc-7-aarch64-linux-gnu gcc-7-s390x-linux-gnu gcc-aarch64-linux-gnu gcc-s390x-linux-gnu -y -q
    - sudo /usr/bin/apt-key adv --no-tty --keyserver hkp://keyserver.ubuntu.com:80 --recv C99B11DEB97541F0
    - sudo apt-add-repository https://cli.github.com/packages
    - sudo apt-get update
    - sudo apt-get install gh
    - sudo apt remove golang-go gccgo-go -y
    - curl -OL https://go.dev/dl/go1.18.1.linux-amd64.tar.gz
    - sha256sum go1.18.1.linux-amd64.tar.gz
    - sudo tar -C /usr/local -xvf go1.18.1.linux-amd64.tar.gz
    - touch ~/.goi
    - echo "export PATH=$PATH:/usr/local/go/bin" >> ~/.goi
    - source ~/.goi
  sshkey_script:
    - mkdir -p ~/.ssh
    - sudo chmod 700 ~/.ssh/
    - sudo rm -rf /root/.ssh
    - git config --global --add safe.directory /tmp/ci/x-ui/src-zip/x-ui
    - git config --global user.name "$USERNAME"
    - git config --global user.email "$EMAIL"
    - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    - touch ~/.ssh/id_ed25519.pub
    - touch ~/.ssh/id_ed25519
    - echo "$SSHKEY1" > ~/.ssh/id_ed25519.pub
    - echo "$SSHKEY2" > ~/.ssh/id_ed25519
    - sudo chmod 400 ~/.ssh/*
    - ssh-keygen -R $(curl ifconfig.me)
  source_script:
    - source ~/.goi
    - sudo mkdir -p /tmp/ci/x-ui/
    - sudo mkdir -p /tmp/ci/platform/
    - sudo chmod 777 /tmp/ci/x-ui/
    - sudo chmod 777 /tmp/ci/platform/
    - git clone -b main --single-branch --depth="1" https://github.com/AikoCute-Offical/X-ui.git /tmp/ci/x-ui/src
    - echo "$VERSIONS By https://github.com/AikoCute-Offical" > /tmp/ci/x-ui/src/config/version
  env-targz_script:
    - sudo mkdir -p /tmp/ci/x-ui/src-zip/x-ui/bin
    - sudo chmod 777 /tmp/ci/x-ui/src-zip/x-ui/bin
    - sudo chmod 777 /tmp/ci/x-ui/src-zip/x-ui
    - sudo chmod 777 /tmp/ci/x-ui/src-zip
    - cp -rv /tmp/ci/x-ui/src/x-ui.service /tmp/ci/x-ui/src-zip/x-ui/
    - cp -rv /tmp/ci/x-ui/src/x-ui.sh /tmp/ci/x-ui/src-zip/x-ui/
    - wget -O /tmp/ci/x-ui/src-zip/x-ui/bin/geoip.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
    - wget -O /tmp/ci/x-ui/src-zip/x-ui/bin/geosite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
  xray_source_script:
    - sudo mkdir -p /tmp/ci/XrayPrebuilt
    - sudo chmod 777 /tmp/ci/XrayPrebuilt
    - git clone -b main --single-branch https://github.com/XTLS/Xray-core.git /tmp/ci/XrayPrebuilt/Xray-core
  xray_build_amd64_script:
    - source ~/.goi
    - cd /tmp/ci/XrayPrebuilt/Xray-core
    - CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o OUT/xray-amd64 -v -trimpath -ldflags "-s -w -buildid=" ./main
  xray_build_arm64_script:
    - source ~/.goi
    - cd /tmp/ci/XrayPrebuilt/Xray-core
    - CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC=aarch64-linux-gnu-gcc  go build -o OUT/xray-arm64 -v -trimpath -ldflags "-s -w -buildid=" ./main
  xray_build_s390x_script:
    - source ~/.goi
    - cd /tmp/ci/XrayPrebuilt/Xray-core
    - CGO_ENABLED=1 GOOS=linux GOARCH=s390x CC=s390x-linux-gnu-gcc  go build -o OUT/xray-s390x -v -trimpath -ldflags "-s -w -buildid=" ./main
  xray_build_riscv64_script:
    - source ~/.goi
    - cd /tmp/ci/XrayPrebuilt/Xray-core
    - CGO_ENABLED=1 GOOS=linux GOARCH=riscv64 CC=riscv64-linux-gnu-gcc  go build -o OUT/xray-riscv64 -v -trimpath -ldflags "-s -w -buildid=" ./main
  amd64_script:
    - source ~/.goi
    - cd /tmp/ci/x-ui/src
    - CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags='-extldflags=-static' -tags sqlite_omit_load_extension -o xui-amd64 -v main.go
    - mv xui-amd64 /tmp/ci/platform/
  arm64_script:
    - source ~/.goi
    - cd /tmp/ci/x-ui/src
    - CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC=aarch64-linux-gnu-gcc go build -ldflags='-extldflags=-static' -tags sqlite_omit_load_extension -o xui-arm64 -v main.go
    - mv xui-arm64 /tmp/ci/platform/
  s390x_script:
    - source ~/.goi
    - cd /tmp/ci/x-ui/src
    - CGO_ENABLED=1 GOOS=linux GOARCH=s390x CC=s390x-linux-gnu-gcc go build -ldflags='-extldflags=-static' -tags sqlite_omit_load_extension -o xui-s390x -v main.go
    - mv xui-s390x /tmp/ci/platform/
  riscv64_script:
    - source ~/.goi
    - cd /tmp/ci/x-ui/src
    - CGO_ENABLED=1 GOOS=linux GOARCH=riscv64 CC=riscv64-linux-gnu-gcc go build -ldflags='-extldflags=-static' -tags sqlite_omit_load_extension -o xui-riscv64 -v main.go
    - mv xui-riscv64 /tmp/ci/platform/
  branch_amd64_script:
    - mv /tmp/ci/platform/xui-amd64 /tmp/ci/x-ui/src-zip/x-ui/x-ui
    - mv /tmp/ci/XrayPrebuilt/Xray-core/OUT/xray-amd64 /tmp/ci/x-ui/src-zip/x-ui/bin/xray-linux-amd64
    - cd /tmp/ci/x-ui/src-zip/x-ui
    - git init && git add -vA && git commit -sm "Release: X-UI $VERSIONS AMD64" && git remote add origin git@github.com:AikoCute-Offical/X-ui.git
    - git checkout -b "X-UI-$VERSIONS-AMD64"
    - echo "yes" | git push -uf origin "X-UI-$VERSIONS-AMD64"
  branch_arm64_script:
    - rm -rvf /tmp/ci/x-ui/src-zip/x-ui/.git
    - rm -rvf /tmp/ci/x-ui/src-zip/x-ui/x-ui
    - rm -rvf /tmp/ci/x-ui/src-zip/x-ui/bin/xray-linux-*
    - mv /tmp/ci/platform/xui-arm64 /tmp/ci/x-ui/src-zip/x-ui/x-ui
    - mv /tmp/ci/XrayPrebuilt/Xray-core/OUT/xray-arm64 /tmp/ci/x-ui/src-zip/x-ui/bin/xray-linux-arm64
    - cd /tmp/ci/x-ui/src-zip/x-ui
    - git init && git add -vA && git commit -sm "Release: X-UI $VERSIONS ARM64" && git remote add origin git@github.com:AikoCute-Offical/X-ui.git
    - git checkout -b "X-UI-$VERSIONS-ARM64"
    - echo "yes" | git push -uf origin "X-UI-$VERSIONS-ARM64"
  branch_s390x_script:
    - rm -rvf /tmp/ci/x-ui/src-zip/x-ui/.git
    - rm -rvf /tmp/ci/x-ui/src-zip/x-ui/x-ui
    - rm -rvf /tmp/ci/x-ui/src-zip/x-ui/bin/xray-linux-*
    - mv /tmp/ci/platform/xui-s390x /tmp/ci/x-ui/src-zip/x-ui/x-ui
    - mv /tmp/ci/XrayPrebuilt/Xray-core/OUT/xray-s390x /tmp/ci/x-ui/src-zip/x-ui/bin/xray-linux-s390x
    - cd /tmp/ci/x-ui/src-zip/x-ui
    - git init && git add -vA && git commit -sm "Release: X-UI $VERSIONS S390X" && git remote add origin git@github.com:AikoCute-Offical/X-ui.git
    - git checkout -b "X-UI-$VERSIONS-S390X"
    - echo "yes" | git push -uf origin "X-UI-$VERSIONS-S390X"
  branch_riscv64_script:
    - rm -rvf /tmp/ci/x-ui/src-zip/x-ui/.git
    - rm -rvf /tmp/ci/x-ui/src-zip/x-ui/x-ui
    - rm -rvf /tmp/ci/x-ui/src-zip/x-ui/bin/xray-linux-*
    - mv /tmp/ci/platform/xui-riscv64 /tmp/ci/x-ui/src-zip/x-ui/x-ui
    - mv /tmp/ci/XrayPrebuilt/Xray-core/OUT/xray-riscv64 /tmp/ci/x-ui/src-zip/x-ui/bin/xray-linux-riscv64
    - cd /tmp/ci/x-ui/src-zip/x-ui
    - git init && git add -vA && git commit -sm "Release: X-UI $VERSIONS RISCV64" && git remote add origin git@github.com:AikoCute-Offical/X-ui.git
    - git checkout -b "X-UI-$VERSIONS-RISCV64"
    - echo "yes" | git push -uf origin "X-UI-$VERSIONS-RISCV64"
  github_script:
    - sudo rm -rf /tmp/ci/*
    - sudo chmod 777 /tmp/ci
    - mkdir -p /tmp/ci/amd64
    - mkdir -p /tmp/ci/arm64
    - mkdir -p /tmp/ci/s390x
    - mkdir -p /tmp/ci/riscv64
    - git clone -b "X-UI-$VERSIONS-AMD64" --single-branch https://github.com/AikoCute-Offical/X-ui.git /tmp/ci/amd64/x-ui
    - cd /tmp/ci/amd64/
    - rm -rvf x-ui/.git
    - tar -czvf x-ui-linux-amd64.tar.gz x-ui
    - cd /
    - git clone -b "X-UI-$VERSIONS-ARM64" --single-branch https://github.com/AikoCute-Offical/X-ui.git /tmp/ci/arm64/x-ui
    - cd /tmp/ci/arm64/
    - rm -rvf x-ui/.git
    - tar -czvf x-ui-linux-arm64.tar.gz x-ui
    - cd /
    - git clone -b "X-UI-$VERSIONS-S390X" --single-branch https://github.com/AikoCute-Offical/X-ui.git /tmp/ci/s390x/x-ui
    - cd /tmp/ci/s390x/
    - rm -rvf x-ui/.git
    - tar -czvf x-ui-linux-s390x.tar.gz x-ui
    - cd /
    - git clone -b "X-UI-$VERSIONS-RISCV64" --single-branch https://github.com/AikoCute-Offical/X-ui.git /tmp/ci/riscv64/x-ui
    - cd /tmp/ci/riscv64/
    - rm -rvf x-ui/.git
    - tar -czvf x-ui-linux-riscv64.tar.gz x-ui
    - cd /
  release_script:
    - cd /tmp/ci
    - git clone -b main --single-branch https://github.com/AikoCute-Offical/X-ui.git
    - mkdir -p /tmp/ci/out/
    - mv /tmp/ci/amd64/x-ui-linux-amd64.tar.gz /tmp/ci/out/
    - mv /tmp/ci/arm64/x-ui-linux-arm64.tar.gz /tmp/ci/out/
    - mv /tmp/ci/s390x/x-ui-linux-s390x.tar.gz /tmp/ci/out/
    - mv /tmp/ci/riscv64/x-ui-linux-riscv64.tar.gz /tmp/ci/out/
    - gh config set git_protocol ssh --host github.com
    - touch mytoken.txt
    - echo "$TOKEN" > mytoken.txt
    - gh auth login --with-token < mytoken.txt
    - bash <(curl -Ls https://raw.githubusercontent.com/AikoCute-Offical/X-ui/main/release.sh)
    - echo "yes" | gh release create $VERSIONS /tmp/ci/out/*.tar.gz --notes "$INFORELEASE" --title "X-UI $VERSIONS - Weekly - $(date +"%d-%m-%Y")"
