env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "CirrusCI"
    CIRRUS_WORKING_DIR: "/tmp/ci"
    TOKEN: "ENCRYPTED[8899d705efa5229bdebf7958f8e6005750663f9a9debc0d5a5d1a3977a182de19f840510f47fa14576e6381db124c443]"
    RCLONE: "ENCRYPTED[1f8f7e7eaf78795dc4106cc960a25dcaf2395de9b39575a5ba34ad7d3fb9dd4679f3f05a3292baf09181916f3f08c60a]"
    RELEASE: "ENCRYPTED[ce13be89c0c70b830928e53fe444ed3749387cd2364a8919bd19a6a4d08f16b597ca3795503e8d8236bb723eea28cf5f]"
    VERSIONS: "0.3.2.1"
    INFORELEASE: "X-UI Vietnamese Language\n\nNgưng support 32Bit\nThêm Bot Telegram và CloudFlare\n\nSupport: amd64, arm64v8a, s390x.\n\n*** Vui lòng tạo Issues nếu có bất kỳ lỗi nào"
    DEBIAN_FRONTEND: "noninteractive"
    SSHKEY2: "ENCRYPTED[!8469040b7a3c804aed48d1626698c53b9f5c665227a91e8a8e3c9c1f73959da955d935bb19f05d1bfc37a1c5e589489f!]"
    SSHKEY1: "ENCRYPTED[!f571f1926b820ceab939cf2786e76cbd6aff9ef70679515414df507cbe7f5f88d24f5f535164ca178736031ebe5bf1b6!]"
    USERNAME: "ENCRYPTED[!84300cf406cc0695b827f4cbc9883c7712ab134798e1347bccac9395580fd618298d6dd1ff7897e77eea3a3203fda42b!]"
    EMAIL: "ENCRYPTED[!a03cbd7c4b2f675b5535c1199bc8bd6eb2f30db7812c7846e372b3e51d00d3c1b4de9e7654bf683c1e5728aba6bfba0e!]"
    GHCONFIG: "ENCRYPTED[!a9370eec9a3e109160953a26c8dc9c4e6625e2a26b241029341baae89fe929a1341a3c8fe115cf69976de1bfcac2e9b9!]"
    GHHOST: "ENCRYPTED[!348343a6388b2af14707d32b2e2b19d101232761579e04804d5144f98dc484ed9bcb500785feb03c64ede236f52ca4bb!]"    

task:
  name: Checked
  only_if: $CIRRUS_REPO_OWNER == 'dopaemon' && $CIRRUS_BRANCH == 'main'
  skip: $CIRRUS_BRANCH != 'main'
  container:
    image: dopaemon/bionic:latest
    cpu: 1
    memory: 1G
  check_script:
    - echo "Checked"

task:
  name: Compile X-UI
  only_if: $CIRRUS_REPO_OWNER == 'dopaemon' && $CIRRUS_BRANCH == 'main'
  skip: $CIRRUS_BRANCH != 'main'
  depends_on:
    - Checked
  container:
    image: dopaemon/bionic:latest
    cpu: 2
    memory: 4G
  install_packages_script:
    - sudo rm -rf /tmp/ci/*
    - sudo apt update
    - sudo apt install software-properties-common jq wget unzip rclone aria2 git gcc-riscv64-linux-gnu gcc-7-aarch64-linux-gnu gcc-7-s390x-linux-gnu gcc-aarch64-linux-gnu gcc-s390x-linux-gnu -y -q
    - sudo apt remove golang-go gccgo-go -y
    - curl -OL https://golang.org/dl/go1.16.7.linux-amd64.tar.gz
    - sha256sum go1.16.7.linux-amd64.tar.gz
    - sudo tar -C /usr/local -xvf go1.16.7.linux-amd64.tar.gz
    - touch ~/.goi
    - echo "export PATH=$PATH:/usr/local/go/bin" >> ~/.goi
    - source ~/.goi
    - mkdir -p ~/.config/rclone
    - echo "$RCLONE" > ~/.config/rclone/rclone.conf
  github_script:
    - mkdir -p ~/.ssh
    - sudo chmod 700 ~/.ssh/
    - sudo rm -rf /root/.ssh
    - git config --global --add safe.directory /tmp/ci/x-ui/src-zip/x-ui
    - git config --global user.name "$USERNAME"
    - git config --global user.email "$EMAIL"
    - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    - touch ~/.ssh/id_ed25519.pub
    - touch ~/.ssh/id_ed25519
    - echo "$SSHKEY1" > ~/.ssh/id_ed25519.pub
    - echo "$SSHKEY2" > ~/.ssh/id_ed25519
    - sudo chmod 400 ~/.ssh/*
    - ssh-keygen -R $(curl ifconfig.me)
  source_script:
    - sudo mkdir -p /tmp/ci/x-ui/
    - sudo mkdir -p /tmp/ci/platform/
    - sudo chmod 777 /tmp/ci/x-ui/
    - sudo chmod 777 /tmp/ci/platform/
    - git clone -b main --single-branch --depth="1" https://github.com/dopaemon/x-ui.git /tmp/ci/x-ui/src
  env-targz_script:
    - sudo mkdir -p /tmp/ci/x-ui/src-zip/x-ui/bin
    - sudo chmod 777 /tmp/ci/x-ui/src-zip/x-ui/bin
    - sudo chmod 777 /tmp/ci/x-ui/src-zip/x-ui
    - sudo chmod 777 /tmp/ci/x-ui/src-zip
    - cp -rv /tmp/ci/x-ui/src/x-ui.service /tmp/ci/x-ui/src-zip/x-ui/
    - cp -rv /tmp/ci/x-ui/src/x-ui.sh /tmp/ci/x-ui/src-zip/x-ui/
    - wget -O /tmp/ci/x-ui/src-zip/x-ui/bin/geoip.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
    - wget -O /tmp/ci/x-ui/src-zip/x-ui/bin/geosite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
  xray_script:
    - sudo mkdir -p /tmp/ci/xray
    - sudo mkdir -p /tmp/ci/xray/amd64
    - sudo mkdir -p /tmp/ci/xray/arm64
    - sudo mkdir -p /tmp/ci/xray/s390x
    - sudo mkdir -p /tmp/ci/xray/riscv64
    - sudo chmod 777 /tmp/ci/xray/*
    - cd /tmp/ci/xray/amd64
    - wget https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
    - unzip Xray-linux-64.zip
    - cd /tmp/ci/xray/arm64
    - wget https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-arm64-v8a.zip
    - unzip Xray-linux-arm64-v8a.zip
    - cd /tmp/ci/xray/s390x
    - wget https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-s390x.zip
    - unzip Xray-linux-s390x.zip
    - cd /tmp/ci/xray/riscv64
    - wget https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-riscv64.zip
    - unzip Xray-linux-riscv64.zip
  amd64_script:
    - source ~/.goi
    - cd /tmp/ci/x-ui/src
    - CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o xui-amd64 -v main.go
    - mv xui-amd64 /tmp/ci/platform/
  arm64_script:
    - source ~/.goi
    - cd /tmp/ci/x-ui/src
    - CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC=aarch64-linux-gnu-gcc go build -o xui-arm64 -v main.go
    - mv xui-arm64 /tmp/ci/platform/
  s390x_script:
    - source ~/.goi
    - cd /tmp/ci/x-ui/src
    - CGO_ENABLED=1 GOOS=linux GOARCH=s390x CC=s390x-linux-gnu-gcc go build -o xui-s390x -v main.go
    - mv xui-s390x /tmp/ci/platform/
  riscv64_script:
    - source ~/.goi
    - cd /tmp/ci/x-ui/src
    - CGO_ENABLED=1 GOOS=linux GOARCH=riscv64 CC=riscv64-linux-gnu-gcc go build -o xui-riscv64 -v main.go
    - mv xui-riscv64 /tmp/ci/platform/
  branch_amd64_script:
    - mv /tmp/ci/platform/xui-amd64 /tmp/ci/x-ui/src-zip/x-ui/x-ui
    - mv /tmp/ci/xray/amd64/xray /tmp/ci/x-ui/src-zip/x-ui/bin/xray-linux-amd64
    - cd /tmp/ci/x-ui/src-zip/x-ui
    - git init && git add -vA && git commit -sm "Release: X-UI $VERSIONS AMD64" && git remote add origin git@github.com:dopaemon/x-ui.git
    - git checkout -b "X-UI-$VERSIONS-AMD64"
    - echo "yes" | git push -uf origin "X-UI-$VERSIONS-AMD64"
  branch_arm64_script:
    - rm -rvf /tmp/ci/x-ui/src-zip/x-ui/.git
    - rm -rvf /tmp/ci/x-ui/src-zip/x-ui/x-ui
    - rm -rvf /tmp/ci/x-ui/src-zip/x-ui/bin/xray-linux-*
    - mv /tmp/ci/platform/xui-arm64 /tmp/ci/x-ui/src-zip/x-ui/x-ui
    - mv /tmp/ci/xray/arm64/xray /tmp/ci/x-ui/src-zip/x-ui/bin/xray-linux-arm64
    - cd /tmp/ci/x-ui/src-zip/x-ui
    - git init && git add -vA && git commit -sm "Release: X-UI $VERSIONS ARM64" && git remote add origin git@github.com:dopaemon/x-ui.git
    - git checkout -b "X-UI-$VERSIONS-ARM64"
    - echo "yes" | git push -uf origin "X-UI-$VERSIONS-ARM64"
  branch_s390x_script:
    - rm -rvf /tmp/ci/x-ui/src-zip/x-ui/.git
    - rm -rvf /tmp/ci/x-ui/src-zip/x-ui/x-ui
    - rm -rvf /tmp/ci/x-ui/src-zip/x-ui/bin/xray-linux-*
    - mv /tmp/ci/platform/xui-s390x /tmp/ci/x-ui/src-zip/x-ui/x-ui
    - mv /tmp/ci/xray/s390x/xray /tmp/ci/x-ui/src-zip/x-ui/bin/xray-linux-s390x
    - cd /tmp/ci/x-ui/src-zip/x-ui
    - git init && git add -vA && git commit -sm "Release: X-UI $VERSIONS S390X" && git remote add origin git@github.com:dopaemon/x-ui.git
    - git checkout -b "X-UI-$VERSIONS-S390X"
    - echo "yes" | git push -uf origin "X-UI-$VERSIONS-S390X"
  branch_risvc64_script:
    - rm -rvf /tmp/ci/x-ui/src-zip/x-ui/.git
    - rm -rvf /tmp/ci/x-ui/src-zip/x-ui/x-ui
    - rm -rvf /tmp/ci/x-ui/src-zip/x-ui/bin/xray-linux-*
    - mv /tmp/ci/platform/xui-riscv64 /tmp/ci/x-ui/src-zip/x-ui/x-ui
    - mv /tmp/ci/xray/riscv64/xray /tmp/ci/x-ui/src-zip/x-ui/bin/xray-linux-risvc64
    - cd /tmp/ci/x-ui/src-zip/x-ui
    - git init && git add -vA && git commit -sm "Release: X-UI $VERSIONS RISVC64" && git remote add origin git@github.com:dopaemon/x-ui.git
    - git checkout -b "X-UI-$VERSIONS-RISVC64"
    - echo "yes" | git push -uf origin "X-UI-$VERSIONS-RISVC64"
task:
  name: Create Github Release
  only_if: $CIRRUS_REPO_OWNER == 'dopaemon' && $CIRRUS_BRANCH == 'main'
  skip: $CIRRUS_BRANCH != 'main'
  depends_on:
    - Compile X-UI
  container:
    image: dopaemon/bionic:latest
    cpu: 2
    memory: 4G
  install_script:
    - sudo apt-get update
    - sudo apt-get install aria2 jq curl wget unzip zip git software-properties-common -y -q
    - sudo /usr/bin/apt-key adv --no-tty --keyserver hkp://keyserver.ubuntu.com:80 --recv C99B11DEB97541F0
    - sudo apt-add-repository https://cli.github.com/packages
    - sudo apt-get update
    - sudo apt-get install gh
  ssh_script:
    - mkdir -p ~/.ssh
    - sudo chmod 700 ~/.ssh/
    - git config --global user.name "$USERNAME"
    - git config --global user.email "$EMAIL"
    - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    - touch ~/.ssh/id_ed25519.pub
    - touch ~/.ssh/id_ed25519
    - echo "$SSHKEY1" > ~/.ssh/id_ed25519.pub
    - echo "$SSHKEY2" > ~/.ssh/id_ed25519
    - sudo chmod 400 ~/.ssh/*
  github_script:
    - sudo rm -rf /tmp/ci/*
    - sudo chmod 777 /tmp/ci
    - mkdir -p /tmp/ci/amd64
    - mkdir -p /tmp/ci/arm64
    - mkdir -p /tmp/ci/s390x
    - mkdir -p /tmp/ci/riscv64
    - git clone -b "X-UI-$VERSIONS-AMD64" --single-branch https://github.com/dopaemon/x-ui.git /tmp/ci/amd64/x-ui
    - cd /tmp/ci/amd64/
    - rm -rvf .git
    - tar -czvf x-ui-linux-amd64.tar.gz x-ui
    - cd /
    - git clone -b "X-UI-$VERSIONS-ARM64" --single-branch https://github.com/dopaemon/x-ui.git /tmp/ci/arm64/x-ui
    - cd /tmp/ci/arm64/
    - rm -rvf .git
    - tar -czvf x-ui-linux-arm64.tar.gz x-ui
    - cd /
    - git clone -b "X-UI-$VERSIONS-S390X" --single-branch https://github.com/dopaemon/x-ui.git /tmp/ci/s390x/x-ui
    - cd /tmp/ci/s390x/
    - rm -rvf .git
    - tar -czvf x-ui-linux-s390x.tar.gz x-ui
    - cd /
    - git clone -b "X-UI-$VERSIONS-RISCV64" --single-branch https://github.com/dopaemon/x-ui.git /tmp/ci/riscv64/x-ui
    - cd /tmp/ci/riscv64/
    - rm -rvf .git
    - tar -czvf x-ui-linux-riscv64.tar.gz x-ui
    - cd /
  release_script:
    - cd /tmp/ci
    - git clone -b main --single-branch https://github.com/dopaemon/x-ui.git
    - mkdir -p /tmp/ci/out/
    - mv /tmp/ci/amd64/x-ui-linux-amd64.tar.gz /tmp/ci/out/
    - mv /tmp/ci/arm64/x-ui-linux-arm64.tar.gz /tmp/ci/out/
    - mv /tmp/ci/s390x/x-ui-linux-s390x.tar.gz /tmp/ci/out/
    - mv /tmp/ci/riscv64/x-ui-linux-riscv64.tar.gz /tmp/ci/out/
    - gh config set git_protocol ssh --host github.com
    - touch mytoken.txt
    - echo "$TOKEN" > mytoken.txt
    - gh auth login --with-token < mytoken.txt
    - bash <(curl -Ls https://raw.githubusercontent.com/dopaemon/x-ui/main/release.sh)
    - echo "yes" | gh release create $VERSIONS /tmp/ci/out/*.tar.gz --notes "$INFORELEASE"
