env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "CirrusCI"
    
    token: "ENCRYPTED[8899d705efa5229bdebf7958f8e6005750663f9a9debc0d5a5d1a3977a182de19f840510f47fa14576e6381db124c443]"

task:
  name: Compile X-UI For X64
  container:
    image: dopaemon/bionic:latest
    cpu: 2
    memory: 4G
  install_packages_script:
    - sudo apt update
    - sudo apt install software-properties-common jq -y
    - sudo apt remove golang-go gccgo-go -y
    - curl -OL https://golang.org/dl/go1.16.7.linux-amd64.tar.gz
    - sudo apt install wget -y && wget https://github.com/tfausak/github-release/releases/download/2.0.0.0/github-release-2.0.0.0-ubuntu && mv github-release-2.0.0.0-ubuntu github && sudo mv github /usr/bin/ && sudo chmod +x /usr/bin/github
    - sha256sum go1.16.7.linux-amd64.tar.gz
    - sudo tar -C /usr/local -xvf go1.16.7.linux-amd64.tar.gz
    - touch ~/.goi
    - echo "export PATH=$PATH:/usr/local/go/bin" >> ~/.goi
    - source ~/.goi
  gitsource_script:
    - source ~/.goi
    - sudo mkdir -p /tmp/x-ui && sudo chmod 777 /tmp/x-ui && cd /tmp/x-ui
    - git clone -b main https://github.com/dopaemon/x-ui.git src && cd src
    - go build main.go
    - cd .. && mkdir -p src-zip && cd src-zip && mkdir -p bin
    - mv ../src/main ../src-zip/x-ui
    - mv ../src/x-ui.service ../src-zip/
    - mv ../src/x-ui.sh ../src-zip/
    - mv ../src/bin/xray-linux-amd64 ../src-zip/bin/
    - mv ../src/bin/geosite.dat ../src-zip/bin/
    - mv ../src/bin/geoip.dat ../src-zip/bin/
    - tar -czvf x-ui-linux-amd64.tar.gz *
    - cp -r /tmp/x-ui/src/github-release.sh ../src-zip/
    - ./github-release.sh
